In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import librosa
import os
import sys
import IPython.display as ipd
from sklearn.metrics import accuracy_score

In [ ]:
dataset_path = '/content/drive/MyDrive/Miniproject/DATASET/English'

In [ ]:
list_dataset=os.listdir(dataset_path)

In [ ]:
list_dataset

['MaleAngry',
 'MaleHappy',
 'MaleSad',
 'MaleNeutral',
 'FemaleAngry',
 'FemaleHappy',
 'FemaleSad',
 'FemaleNeutral']

In [ ]:
dataset=pd.DataFrame(columns=['feature'])
n_dataset=pd.DataFrame(columns=['label'])
ct=0
counter=0

In [ ]:
length=len(list_dataset)

for i in range(0,length):
    k=os.listdir(dataset_path+'/'+list_dataset[i])
    j=len(k)
    for u in range(0,j):
        z=list_dataset[i]
        if(z[4]=='h' or z[4]=='H' or z[6]=='h' or z[6]=='H'):
            n_dataset.loc[ct]='Happy'
        elif(z[4]=='a' or z[4]=='A' or z[6]=='a' or z[6]=='A'):
            n_dataset.loc[ct]='Angry'
        elif(z[4]=='n' or z[4]=='N' or z[6]=='n' or z[6]=='N'):
            n_dataset.loc[ct]='Neutral'
        elif(z[4]=='s' or z[4]=='S' or z[6]=='s' or z[6]=='S'):
            n_dataset.loc[ct]='Sad'
        
        ct=ct+1

        X,sample_rate=librosa.load(dataset_path+'/'+list_dataset[i]+'/'+k[u],res_type='kaiser_fast',duration=2.5,sr=22050*2,offset=0.5)
        sample_rate=np.array(sample_rate)
        mfcc=librosa.feature.mfcc(y=X,sr=sample_rate,n_mfcc=13)
        mfcc=np.mean(mfcc,axis=0)
        dataset.loc[counter]=[mfcc]
        counter=counter+1

In [ ]:
dataset = pd.concat([n_dataset,pd.DataFrame(dataset['feature'].values.tolist())],axis=1)

In [ ]:
dataset=dataset.fillna(0)

In [ ]:
y=dataset.iloc[:,0]
X=dataset.iloc[:,1:218]

In [ ]:
dataset=dataset.fillna(0)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

3472
868
3472
868


In [ ]:
mean=np.mean(X_train,axis=0)
std=np.std(X_train,axis=0)

X_train=(X_train-mean)/std
X_test=(X_test-mean)/std

**DECISION TREE CLASSIFIER**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 97  40  27  48]
 [ 44  72  42  43]
 [ 34  37 100  36]
 [ 41  38  47 122]]
              precision    recall  f1-score   support

       Angry       0.45      0.46      0.45       212
       Happy       0.39      0.36      0.37       201
     Neutral       0.46      0.48      0.47       207
         Sad       0.49      0.49      0.49       248

    accuracy                           0.45       868
   macro avg       0.45      0.45      0.45       868
weighted avg       0.45      0.45      0.45       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 45.05%


**KNN CLASSIFIER**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[110  38  35  29]
 [ 35 105  38  23]
 [ 19  44 125  19]
 [ 32  47  52 117]]
              precision    recall  f1-score   support

       Angry       0.56      0.52      0.54       212
       Happy       0.45      0.52      0.48       201
     Neutral       0.50      0.60      0.55       207
         Sad       0.62      0.47      0.54       248

    accuracy                           0.53       868
   macro avg       0.53      0.53      0.53       868
weighted avg       0.54      0.53      0.53       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 52.65%


**NB CLASSIFIER**

In [ ]:
from sklearn.naive_bayes import GaussianNB

model =GaussianNB().fit(X_train, y_train)

In [ ]:
import numpy as np
predicted = model.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predicted))
print(classification_report(y_test,y_pred))

[[ 91  48  15  58]
 [ 55  52  22  72]
 [ 53  52  41  61]
 [ 67  41  11 129]]
              precision    recall  f1-score   support

       Angry       0.31      0.56      0.40       212
       Happy       0.25      0.06      0.10       201
     Neutral       0.32      0.51      0.39       207
         Sad       0.38      0.17      0.23       248

    accuracy                           0.32       868
   macro avg       0.31      0.32      0.28       868
weighted avg       0.32      0.32      0.28       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=predicted)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 36.06%


**RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=20, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[121  41  23  27]
 [ 33 113  23  32]
 [ 26  37 111  33]
 [ 38  39  28 143]]
              precision    recall  f1-score   support

       Angry       0.56      0.57      0.56       212
       Happy       0.49      0.56      0.52       201
     Neutral       0.60      0.54      0.57       207
         Sad       0.61      0.58      0.59       248

    accuracy                           0.56       868
   macro avg       0.56      0.56      0.56       868
weighted avg       0.57      0.56      0.56       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 56.22%


**SVM CLASSIFIER**

**LINEAR SVM**

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 87  50  32  43]
 [ 56  68  32  45]
 [ 30  47  83  47]
 [ 54  41  39 114]]
              precision    recall  f1-score   support

       Angry       0.38      0.41      0.40       212
       Happy       0.33      0.34      0.33       201
     Neutral       0.45      0.40      0.42       207
         Sad       0.46      0.46      0.46       248

    accuracy                           0.41       868
   macro avg       0.40      0.40      0.40       868
weighted avg       0.41      0.41      0.41       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 40.55%


**KERNAL SVM**

**Polynomial Kernel **

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=8, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 52 140  10  10]
 [  5 169  18   9]
 [  9 138  49  11]
 [  8 167  26  47]]
              precision    recall  f1-score   support

       Angry       0.70      0.25      0.36       212
       Happy       0.28      0.84      0.41       201
     Neutral       0.48      0.24      0.32       207
         Sad       0.61      0.19      0.29       248

    accuracy                           0.37       868
   macro avg       0.52      0.38      0.35       868
weighted avg       0.52      0.37      0.34       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 36.52%


**Gaussian Kernel**

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 83  61  22  46]
 [ 27  92  30  52]
 [ 21  36 104  46]
 [ 39  53  26 130]]
              precision    recall  f1-score   support

       Angry       0.49      0.39      0.43       212
       Happy       0.38      0.46      0.42       201
     Neutral       0.57      0.50      0.53       207
         Sad       0.47      0.52      0.50       248

    accuracy                           0.47       868
   macro avg       0.48      0.47      0.47       868
weighted avg       0.48      0.47      0.47       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 47.12%


**Sigmoid Kernel**

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[118  14  58  22]
 [ 84  12  75  30]
 [ 76  10 106  15]
 [102  12  93  41]]
              precision    recall  f1-score   support

       Angry       0.31      0.56      0.40       212
       Happy       0.25      0.06      0.10       201
     Neutral       0.32      0.51      0.39       207
         Sad       0.38      0.17      0.23       248

    accuracy                           0.32       868
   macro avg       0.31      0.32      0.28       868
weighted avg       0.32      0.32      0.28       868



In [ ]:
# Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)
# Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 31.91%
